create extension if not exists pgcrypto;
create table if not exists public.menu_items(
 id bigint generated by default as identity primary key,name_ar text not null,name_en text not null,
 description_ar text,description_en text,category text not null default 'mains',price numeric(12,2) not null,
 image_url text,active boolean not null default true,sort_order int not null default 0,created_at timestamptz not null default now());
create table if not exists public.orders(
 id uuid primary key default gen_random_uuid(),table_number int not null check(table_number between 1 and 30),
 status text not null default 'new' check(status in('new','preparing','ready','served','paid','cancelled')),
 total numeric(12,2) not null default 0,payment_method text,payment_status text not null default 'unpaid',
 created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.order_items(
 id bigint generated by default as identity primary key,order_id uuid not null references public.orders(id) on delete cascade,
 menu_item_id bigint,name text,name_ar text,name_en text,price numeric(12,2) not null,quantity int not null check(quantity>0));
alter table public.menu_items enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security;
create policy "public read active menu" on public.menu_items for select using(active=true);
create policy "public create orders" on public.orders for insert with check(table_number between 1 and 30);
create policy "public read orders" on public.orders for select using(true);
create policy "public create order items" on public.order_items for insert with check(true);
create policy "public read order items" on public.order_items for select using(true);
-- Enable Realtime for orders/order_items/menu_items from Supabase Dashboard.
